version: '4.0'

services:
  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt
    restart: always
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./mosquitto-no-auth.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto.acl:/mosquitto/config/mosquitto.acl
      - ./mosquitto.passwd:/mosquitto/config/mosquitto.passwd
    environment:
      - TZ=America/Santiago
      - PUID=1883
      - PGID=1883
  
  sub:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sub
    restart: always
    volumes:
      - ./backend:/backend
    depends_on:
      - grafana
  
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=ammpio-mqtt-datasource
      - GF_INSTALL_PLUGINS=https://github.com/svet-b/grafana-mqtt-datasource/archive/refs/heads/built.zip;ammpio-mqtt-datasource
      - GF_SECURITY_ADMIN_PASSWORD=hola123
      - GF_SECURITY_ADMIN_USER=hola123
      - GF_SECURITY_ALLOW_EMBEDDING=true
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - grafana-data:/var/lib/grafana
      - ./grafana/plugins:/var/lib/grafana/plugins
      
volumes:
  grafana-data: