# using Nginx base image
FROM nginx
# delete nginx default .conf .file
RUN rm /etc/nginx/conf.d/default.conf
# add the .conf file we have created
COPY nginx-prod.conf /etc/nginx/nginx.conf
COPY certs/grafana.crt /etc/nginx/grafana.crt
COPY certs/grafana.key /etc/nginx/grafana.key